export interface GetClassList {
  data: Data;
}

export interface Data {
  coach: Coach;
  user: User;
}

export interface Coach {
  __typename: "User";
  id: string;
  isEnrolledInAIGuide: boolean;
  isFormalTeacher: boolean;
  isK4dTeacher: boolean;
  isKmapTeacher: boolean;
  kaid: string;
  key: string;
  schoolAffiliation: null;
  studentLists: StudentList[];
  userDistrictInfos: any[];
}

export interface StudentList {
  __typename: "StudentList";
  autoGenerated: boolean;
  cacheId: string;
  classroomDistrictInfo: null;
  coachKaid: string;
  countStudents: number;
  id: string;
  includesSat: boolean;
  key: string;
  name: string;
  signupCode: string;
  topics: Topic[];
}

export interface Topic {
  __typename: "Topic";
  domainSlug: string;
  iconPath: string;
  id: string;
  learnableContentSummary: LearnableContentSummary;
  slug: string;
  title: string;
  translatedStandaloneTitle: string;
}

export interface LearnableContentSummary {
  __typename: "LearnableContentSummary";
  countExercises: number;
}

export interface User {
  __typename: "User";
  id: string;
  tosForFormalTeacherStatus: null;
}
